### ISSUE TITLE
Simplify CSS snippet

### ISSUE THREAD

**Issue by davelab6** [etunni/Arapey-Minisite#53]
```
* {
--opsz: 12;
font-variation-settings: "opsz" var(--opsz);
}


.arapey {
--opsz: 81;
font-family: "Arapey";
font-weight: 650;
}
```

- [ ] Should be simplified to

```
.arapey {
font-family: "Arapey";
font-weight: 650;
font-optical-sizing: auto;
font-size: 100px;
}
```

- [ ] Add 1 more paragraph to the text above that explains browsers should apply optical size automatically when it is avaiilable, via `font-optical-sizing` property

**Comment by RoelN** [comment]
@davelab6 Tried to combine both into one, what do you think?

```CSS
.arapey {
  font-family: "Arapey";     /* Apply the font */ 
  font-weight: 500;          /* Apply the weight */ 
  font-size: 320px;          /* Apply the size */ 
  font-optical-sizing: auto; /* Optimise optical size for this font-size */ 
}
```
